version: "3.9"

services:
  web:
    build: .
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - default

    # vue_cli:
    #   image: ebiven/vue-cli
    #   init: True
    #   working_dir: /code
    #   command: >
    #     /bin/sh -c "npm i; npm run serve"
    #   volumes:
    #     - ./frontend:/code
    #   ports:
    #     - "8080:8080"
    #   networks:
    #     - default