# Generated by Django 3.2.7 on 2021-09-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210925_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='supervisors',
            new_name='supervisor',
        ),
    ]
